use clap::{Arg, ArgAction, Command};

pub(crate) fn command() -> Command {
    Command::new("cargo stopwatch-server")
        .about("Server daemon for the cargo stopwatch cli tool")
        .version("0.1.0")
        .author("Amelia Rossi")
        .subcommand(Command::new("start")
            .about("Starts the server")
            .arg(Arg::new("port")
                .help("Port for the server to run on.")
                .short('p')
                .long("port")
                .action(ArgAction::Set)
                .value_name("PORT")
                .default_value("44355"))
            .arg(Arg::new("timeout")
                .help("Server timeout in minutes.")
                .short('t').long("timeout")
                .action(ArgAction::Set)
                .value_name("TIMEOUT")
                .default_value("10"))
            .arg(Arg::new("quiet mode")
                .help("Don't display package name or command on discord")
                .short('q')
                .long("quiet")
                .action(ArgAction::SetTrue)))
        .subcommand(Command::new("alive").about("Check if the server is running").long_about("Check if the server is running, exits with 0 if the server is running or 1 if the server is not"))
}
