[package]
name = "cargo-stopwatch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.40"
fork = "0.2.0"
serde_json = "1.0.140"
stopwatch-protocol = { path = "../stopwatch-protocol"}
tokio = {version = "1.45.1", features = ["full"]}
